[tool.poetry]
name = "geekshop"
version = "0.1.0"
description = ""
authors = ["kadr <kadr_job@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^9.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
